version: '3.3'

services:

  tubecast:
    build:
      context: ./
    image: tubecast
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
    environment:
      NODE_PATH: "./lib"
      NODE_ENV: "production"
